### ISSUE TITLE
[REQ] Metamod

### ISSUE THREAD

**Issue by ghostt187** [K4ryuu/CS2_PlaytimeTracker#1]
woudnt it be better to use metamod for thi splugin and some other of ur plugins since most of us are using cs2fixes and counterstrikesharp doesnt work together with cs2fixes

**Comment by K4ryuu** [comment]
Hello,

CS2Fixes is a rather limited addon, and many of its functions can already be effectively replaced by various CSS community plugins. CSS remains in active community development, with new plugins being continuously added also by the community. This provides an equally accessible platform for both experienced SourcePawn developers, aspiring C# newcomers, and seasoned veterans to create content for CS2.

Overall, opting for a more scalable solution within the CSS community appears to be the wiser choice for me. Perhaps in the future, there may be opportunities for mutual support between the two.

Wishing you a fantastic day!

**Comment by K4ryuu** [comment]
We have found a way for the compatibility. Contact me on Discord for further information.
